-- =============================================================================
-- seed.sql
-- Seed data for Temperies Mundial
-- Source of truth: server/prisma/seed.js (29 users + 72 World Cup 2026 matches)
-- No predictions — those are user-generated at runtime.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Users (1 admin + 28 employees)
-- Passwords are stored in plain text to match the existing Express backend.
-- IDs are generated by Supabase (gen_random_uuid()).
-- ---------------------------------------------------------------------------

INSERT INTO users (username, name, password, role, avatar_seed, legacy_exact_matches, legacy_diff_matches, legacy_outcome_matches) VALUES
  ('admin', 'Administrador', 'adminmundial2026', 'admin', 'admin', 0, 0, 0),
  ('eduardo.rodriguez', 'Eduardo Rodriguez', 'edu.941', 'user', 'emp-1', 0, 0, 0),
  ('gabriel.vergara', 'Gabriel Vergara', 'gab.728', 'user', 'emp-2', 0, 0, 0),
  ('matias.mercado', 'Matias Mercado', 'mat.109', 'user', 'emp-3', 0, 0, 0),
  ('alejandro.riccillo', 'Alejandro Riccillo', 'ale.852', 'user', 'emp-4', 0, 0, 0),
  ('claudio.mazolli', 'Claudio Mazolli', 'cla.491', 'user', 'emp-5', 0, 0, 0),
  ('ramiro.toulemonde', 'Ramiro Toulemonde', 'ram.305', 'user', 'emp-6', 0, 0, 0),
  ('yesica.arevalo', 'Yesica Arevalo', 'yes.673', 'user', 'emp-7', 0, 0, 0),
  ('federico.martinez', 'Federico Martinez', 'fed.214', 'user', 'emp-8', 0, 0, 0),
  ('mauricio.aiello', 'Mauricio Aiello', 'mau.836', 'user', 'emp-9', 0, 0, 0),
  ('milagros.aranzabe', 'Milagros Aranzabe', 'mil.198', 'user', 'emp-10', 0, 0, 0),
  ('rocio.smidt', 'Rocio Smidt', 'roc.542', 'user', 'emp-11', 0, 0, 0),
  ('alejandro.morreale', 'Alejandro Morreale', 'mor.703', 'user', 'emp-12', 0, 0, 0),
  ('daiana.amarante', 'Daiana Amarante', 'dai.619', 'user', 'emp-13', 0, 0, 0),
  ('leandro.saraceno', 'Leandro Saraceno', 'lea.285', 'user', 'emp-14', 0, 0, 0),
  ('franco.flores', 'Franco Flores', 'fra.390', 'user', 'emp-15', 0, 0, 0),
  ('nicola.cocciaretti', 'Nicola Cocciaretti', 'nic.571', 'user', 'emp-16', 0, 0, 0),
  ('guido.arce', 'Guido Arce', 'gui.843', 'user', 'emp-17', 0, 0, 0),
  ('joaquin.burgos', 'Joaquin Burgos', 'joa.167', 'user', 'emp-18', 0, 0, 0),
  ('lucas.gil', 'Lucas Gil', 'luc.902', 'user', 'emp-19', 0, 0, 0),
  ('matias.dieguez', 'Matias Dieguez', 'die.384', 'user', 'emp-20', 0, 0, 0),
  ('nacho', 'Nacho', 'nac.750', 'user', 'emp-21', 0, 0, 0),
  ('conrado.blanco', 'Conrado Blanco', 'con.426', 'user', 'emp-22', 0, 0, 0),
  ('dolores.bruzzone', 'Dolores Bruzzone', 'dol.824', 'user', 'emp-23', 0, 0, 0),
  ('julieta.belsito', 'Julieta Belsito', 'jul.375', 'user', 'emp-24', 0, 0, 0),
  ('florencia.belsito', 'Florencia Belsito', 'flo.849', 'user', 'emp-25', 0, 0, 0),
  ('ailen.fleites', 'Ailen Fleites', 'ail.716', 'user', 'emp-26', 0, 0, 0),
  ('vanesa.dellaqua', 'Vanesa DellAqua', 'van.392', 'user', 'emp-27', 0, 0, 0),
  ('guillermo.belsito', 'Guillermo Belsito', 'gui.684', 'user', 'emp-28', 0, 0, 0);

-- ---------------------------------------------------------------------------
-- Matches (72 World Cup 2026 group stage matches)
-- Generated by the same deterministic algorithm as server/prisma/seed.js.
-- IDs are TEXT PKs in "M01"–"M72" format (not sequential by match number —
-- they are sorted by date, so M01 is the earliest match chronologically).
-- home_team / away_team store the 2-letter country code (e.g. 'mx', 'ar').
-- ---------------------------------------------------------------------------

INSERT INTO matches (id, home_team, away_team, date, "group", home_score, away_score, status, stadium) VALUES
  ('M01', 'mx', 'za', '2026-06-11T19:00:00.000Z', 'A', NULL, NULL, 'scheduled', 'AT&T Stadium, Dallas'),
  ('M02', 'kr', 'cz', '2026-06-12T02:00:00.000Z', 'A', NULL, NULL, 'scheduled', 'AT&T Stadium, Dallas'),
  ('M07', 'ca', 'ba', '2026-06-12T19:00:00.000Z', 'B', NULL, NULL, 'scheduled', 'Estadio BBVA, Monterrey'),
  ('M19', 'us', 'py', '2026-06-13T01:00:00.000Z', 'D', NULL, NULL, 'scheduled', 'Hard Rock Stadium, Miami'),
  ('M08', 'qa', 'ch', '2026-06-13T19:00:00.000Z', 'B', NULL, NULL, 'scheduled', 'MetLife Stadium, NY/NJ'),
  ('M13', 'br', 'ma', '2026-06-13T22:00:00.000Z', 'C', NULL, NULL, 'scheduled', 'Estadio Akron, Guadalajara'),
  ('M14', 'ht', 'gb-sct', '2026-06-14T01:00:00.000Z', 'C', NULL, NULL, 'scheduled', 'SoFi Stadium, Los Ángeles'),
  ('M20', 'au', 'tr', '2026-06-14T04:00:00.000Z', 'D', NULL, NULL, 'scheduled', 'AT&T Stadium, Dallas'),
  ('M25', 'de', 'cw', '2026-06-14T17:00:00.000Z', 'E', NULL, NULL, 'scheduled', 'MetLife Stadium, NY/NJ'),
  ('M31', 'nl', 'jp', '2026-06-14T20:00:00.000Z', 'F', NULL, NULL, 'scheduled', 'Lumen Field, Seattle'),
  ('M26', 'ci', 'ec', '2026-06-14T23:00:00.000Z', 'E', NULL, NULL, 'scheduled', 'Hard Rock Stadium, Miami'),
  ('M32', 'se', 'tn', '2026-06-15T02:00:00.000Z', 'F', NULL, NULL, 'scheduled', 'Hard Rock Stadium, Miami'),
  ('M43', 'es', 'cv', '2026-06-15T16:00:00.000Z', 'H', NULL, NULL, 'scheduled', 'BC Place, Vancouver'),
  ('M37', 'be', 'eg', '2026-06-15T19:00:00.000Z', 'G', NULL, NULL, 'scheduled', 'AT&T Stadium, Dallas'),
  ('M38', 'ir', 'nz', '2026-06-16T02:00:00.000Z', 'G', NULL, NULL, 'scheduled', 'Estadio Akron, Guadalajara'),
  ('M55', 'ar', 'dz', '2026-06-17T01:00:00.000Z', 'J', NULL, NULL, 'scheduled', 'Estadio Akron, Guadalajara'),
  ('M44', 'sa', 'uy', '2026-06-17T19:00:00.000Z', 'H', NULL, NULL, 'scheduled', 'Levi''s Stadium, San Francisco'),
  ('M49', 'fr', 'sn', '2026-06-17T22:00:00.000Z', 'I', NULL, NULL, 'scheduled', 'Levi''s Stadium, San Francisco'),
  ('M50', 'iq', 'no', '2026-06-18T01:00:00.000Z', 'I', NULL, NULL, 'scheduled', 'Lumen Field, Seattle'),
  ('M56', 'at', 'jo', '2026-06-18T04:00:00.000Z', 'J', NULL, NULL, 'scheduled', 'Levi''s Stadium, San Francisco'),
  ('M04', 'za', 'cz', '2026-06-18T16:00:00.000Z', 'A', NULL, NULL, 'scheduled', 'Estadio Azteca, CDMX'),
  ('M61', 'pt', 'cd', '2026-06-18T17:00:00.000Z', 'K', NULL, NULL, 'scheduled', 'Estadio Akron, Guadalajara'),
  ('M10', 'ba', 'ch', '2026-06-18T19:00:00.000Z', 'B', NULL, NULL, 'scheduled', 'BMO Field, Toronto'),
  ('M67', 'gb-eng', 'hr', '2026-06-18T20:00:00.000Z', 'L', NULL, NULL, 'scheduled', 'Estadio BBVA, Monterrey'),
  ('M09', 'ca', 'qa', '2026-06-18T22:00:00.000Z', 'B', NULL, NULL, 'scheduled', 'MetLife Stadium, NY/NJ'),
  ('M62', 'uz', 'co', '2026-06-18T23:00:00.000Z', 'K', NULL, NULL, 'scheduled', 'Estadio Azteca, CDMX'),
  ('M03', 'mx', 'kr', '2026-06-19T01:00:00.000Z', 'A', NULL, NULL, 'scheduled', 'Lumen Field, Seattle'),
  ('M68', 'gh', 'pa', '2026-06-19T02:00:00.000Z', 'L', NULL, NULL, 'scheduled', 'Estadio BBVA, Monterrey'),
  ('M21', 'us', 'au', '2026-06-19T19:00:00.000Z', 'D', NULL, NULL, 'scheduled', 'Estadio BBVA, Monterrey'),
  ('M16', 'ma', 'gb-sct', '2026-06-19T22:00:00.000Z', 'C', NULL, NULL, 'scheduled', 'Estadio Akron, Guadalajara'),
  ('M15', 'br', 'ht', '2026-06-20T01:00:00.000Z', 'C', NULL, NULL, 'scheduled', 'SoFi Stadium, Los Ángeles'),
  ('M22', 'py', 'tr', '2026-06-20T03:00:00.000Z', 'D', NULL, NULL, 'scheduled', 'Estadio BBVA, Monterrey'),
  ('M33', 'nl', 'se', '2026-06-20T17:00:00.000Z', 'F', NULL, NULL, 'scheduled', 'SoFi Stadium, Los Ángeles'),
  ('M27', 'de', 'ci', '2026-06-20T20:00:00.000Z', 'E', NULL, NULL, 'scheduled', 'Mercedes-Benz Stadium, Atlanta'),
  ('M28', 'cw', 'ec', '2026-06-21T00:00:00.000Z', 'E', NULL, NULL, 'scheduled', 'Mercedes-Benz Stadium, Atlanta'),
  ('M34', 'jp', 'tn', '2026-06-21T04:00:00.000Z', 'F', NULL, NULL, 'scheduled', 'BMO Field, Toronto'),
  ('M40', 'eg', 'nz', '2026-06-22T16:00:00.000Z', 'G', NULL, NULL, 'scheduled', 'Estadio Azteca, CDMX'),
  ('M46', 'cv', 'uy', '2026-06-22T19:00:00.000Z', 'H', NULL, NULL, 'scheduled', 'Estadio BBVA, Monterrey'),
  ('M45', 'es', 'sa', '2026-06-22T22:00:00.000Z', 'H', NULL, NULL, 'scheduled', 'Estadio Akron, Guadalajara'),
  ('M39', 'be', 'ir', '2026-06-23T01:00:00.000Z', 'G', NULL, NULL, 'scheduled', 'Hard Rock Stadium, Miami'),
  ('M57', 'ar', 'at', '2026-06-23T19:00:00.000Z', 'J', NULL, NULL, 'scheduled', 'Estadio Akron, Guadalajara'),
  ('M52', 'sn', 'no', '2026-06-23T22:00:00.000Z', 'I', NULL, NULL, 'scheduled', 'Estadio Akron, Guadalajara'),
  ('M51', 'fr', 'iq', '2026-06-24T01:00:00.000Z', 'I', NULL, NULL, 'scheduled', 'Estadio BBVA, Monterrey'),
  ('M58', 'dz', 'jo', '2026-06-24T03:00:00.000Z', 'J', NULL, NULL, 'scheduled', 'BMO Field, Toronto'),
  ('M69', 'gb-eng', 'gh', '2026-06-24T17:00:00.000Z', 'L', NULL, NULL, 'scheduled', 'Estadio Akron, Guadalajara'),
  ('M11', 'ca', 'ch', '2026-06-24T19:00:00.000Z', 'B', NULL, NULL, 'scheduled', 'Estadio Azteca, CDMX'),
  ('M12', 'ba', 'qa', '2026-06-24T19:00:00.000Z', 'B', NULL, NULL, 'scheduled', 'Lumen Field, Seattle'),
  ('M63', 'pt', 'uz', '2026-06-24T20:00:00.000Z', 'K', NULL, NULL, 'scheduled', 'Mercedes-Benz Stadium, Atlanta'),
  ('M17', 'br', 'gb-sct', '2026-06-24T22:00:00.000Z', 'C', NULL, NULL, 'scheduled', 'Estadio Azteca, CDMX'),
  ('M18', 'ma', 'ht', '2026-06-24T22:00:00.000Z', 'C', NULL, NULL, 'scheduled', 'BC Place, Vancouver'),
  ('M64', 'cd', 'co', '2026-06-25T00:00:00.000Z', 'K', NULL, NULL, 'scheduled', 'Lumen Field, Seattle'),
  ('M05', 'mx', 'cz', '2026-06-25T01:00:00.000Z', 'A', NULL, NULL, 'scheduled', 'MetLife Stadium, NY/NJ'),
  ('M06', 'za', 'kr', '2026-06-25T01:00:00.000Z', 'A', NULL, NULL, 'scheduled', 'BMO Field, Toronto'),
  ('M70', 'hr', 'pa', '2026-06-25T04:00:00.000Z', 'L', NULL, NULL, 'scheduled', 'Mercedes-Benz Stadium, Atlanta'),
  ('M29', 'de', 'ec', '2026-06-25T20:00:00.000Z', 'E', NULL, NULL, 'scheduled', 'Hard Rock Stadium, Miami'),
  ('M30', 'cw', 'ci', '2026-06-25T20:00:00.000Z', 'E', NULL, NULL, 'scheduled', 'BMO Field, Toronto'),
  ('M35', 'nl', 'tn', '2026-06-25T23:00:00.000Z', 'F', NULL, NULL, 'scheduled', 'Hard Rock Stadium, Miami'),
  ('M36', 'jp', 'se', '2026-06-25T23:00:00.000Z', 'F', NULL, NULL, 'scheduled', 'Estadio Azteca, CDMX'),
  ('M23', 'us', 'tr', '2026-06-26T02:00:00.000Z', 'D', NULL, NULL, 'scheduled', 'Estadio Akron, Guadalajara'),
  ('M24', 'py', 'au', '2026-06-26T02:00:00.000Z', 'D', NULL, NULL, 'scheduled', 'Estadio Akron, Guadalajara'),
  ('M47', 'es', 'uy', '2026-06-28T19:00:00.000Z', 'H', NULL, NULL, 'scheduled', 'MetLife Stadium, NY/NJ'),
  ('M48', 'cv', 'sa', '2026-06-28T19:00:00.000Z', 'H', NULL, NULL, 'scheduled', 'Mercedes-Benz Stadium, Atlanta'),
  ('M53', 'fr', 'no', '2026-06-28T22:00:00.000Z', 'I', NULL, NULL, 'scheduled', 'BMO Field, Toronto'),
  ('M54', 'sn', 'iq', '2026-06-28T22:00:00.000Z', 'I', NULL, NULL, 'scheduled', 'SoFi Stadium, Los Ángeles'),
  ('M41', 'be', 'nz', '2026-06-29T01:00:00.000Z', 'G', NULL, NULL, 'scheduled', 'AT&T Stadium, Dallas'),
  ('M42', 'eg', 'ir', '2026-06-29T01:00:00.000Z', 'G', NULL, NULL, 'scheduled', 'BC Place, Vancouver'),
  ('M65', 'pt', 'co', '2026-06-29T20:00:00.000Z', 'K', NULL, NULL, 'scheduled', 'BC Place, Vancouver'),
  ('M66', 'cd', 'uz', '2026-06-29T20:00:00.000Z', 'K', NULL, NULL, 'scheduled', 'Lumen Field, Seattle'),
  ('M71', 'gb-eng', 'pa', '2026-06-29T23:00:00.000Z', 'L', NULL, NULL, 'scheduled', 'MetLife Stadium, NY/NJ'),
  ('M72', 'hr', 'gh', '2026-06-29T23:00:00.000Z', 'L', NULL, NULL, 'scheduled', 'Hard Rock Stadium, Miami'),
  ('M59', 'ar', 'jo', '2026-06-30T02:00:00.000Z', 'J', NULL, NULL, 'scheduled', 'Estadio BBVA, Monterrey'),
  ('M60', 'dz', 'at', '2026-06-30T02:00:00.000Z', 'J', NULL, NULL, 'scheduled', 'Lumen Field, Seattle');
